# Site settings
title: Salih Gürkan Süerdem
email: sgsuerdem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "/sgsuerdem.com" # the subpath of your site, e.g. /blog/
url: "http://phalegethon.github.io/" # the base hostname & protocol for your site
twitter_username: Phalegethon
github_username:  Phalegethon

# Build settings
markdown: kramdown
highlighter: pygments

include:
  - .nojekyll

exclude:
- "bower_components"
- "bower.json"
- "node_modules"
- "package.json"
- "Gruntfile.coffee"
- "Rakefile"
